# Generated by Django 3.2 on 2022-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='person',
        ),
        migrations.AddField(
            model_name='car',
            name='person',
            field=models.ManyToManyField(to='home.Person'),
        ),
    ]
